app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

//<script type="text/javascript" src="https://secure.skypeassets.com/i/scom/js/skype-uri.js"></script>
//<div id="SkypeButton_Call_smodav_1">
// <script type="text/javascript">
//    Skype.ui({
// "name": "dropdown",
// "element": "SkypeButton_Call_smodav_1",
// "participants": ["smodav"],
// "imageSize": 24
// });
// </script>
//</div>

use App\Http\Controllers\Auth\AdminAuthController;
use Illuminate\Contracts\Mail\Mailer;
use Illuminate\Http\Request;
use SmoDav\Models\Business;

Route::get('/', function () {
    return view('welcome');
});
Route::get('api/search', 'SearchController@getResults');
Route::get('api/search/businesses', 'SearchController@getBusinesses');
Route::get('api/search/business', 'SearchController@getBusinessBySlug');
Route::get('api/search/fieldBusinesses', 'SearchController@getFieldBusinessesBySlug');
Route::get('api/search/fields', 'SearchController@getFields');
Route::get('api/featured', 'SearchController@getFeatured');
Route::get('api/refresh', 'SearchController@refreshIndex');
Route::post('api/inquiry', function (Request $request, Mailer $mailer) {
    $data = $request->all();
    $business = Business::whereSlug($data['slug'])->first();

    $mailer->send('emails.contact', ['data' => $data], function ($message) use ($data, $business) {
        $message
            ->from($data['email'], $data['name'])
            ->to($business->email)
            ->subject('Inquiry from Contact Form' . $data['subject']);
    });

    return 'success';
});

Route::post('api/contact', function (Request $request, Mailer $mailer) {
    $data = $request->all();
    $mailer->send('emails.contact', ['data' => $data], function ($message) use ($data) {
        $message
            ->from($data['email'], $data['name'])
            ->to('info@mtangaza.com')
            ->subject('Inquiry from Contact Form' . $data['subject']);
    });
    return 'success';
});

Route::group(['middleware' => ['guest']], function () {
    $admin = AdminAuthController::ADMIN_URL;
    Route::get($admin . '/login', ['as' => 'admin.login.index', 'uses' => 'Auth\AdminAuthController@getLogin']);
    Route::post($admin . '/login', ['as' => 'admin.login.store', 'uses' => 'Auth\AdminAuthController@postLogin']);
    Route::get('client/login', ['as' => 'client.login.index', 'uses' => 'Auth\ClientAuthController@getLogin']);
    Route::post('client/login', ['as' => 'client.login.store', 'uses' => 'Auth\ClientAuthController@postLogin']);
});

Route::group(['prefix' => 'client', 'middleware' => ['client']], function () {
    Route::get('/', ['as' => 'client.home', 'uses' => 'Client\ClientPagesController@home']);
    Route::get('/logout', ['as' => 'client.login.destroy', 'uses' => 'Auth\ClientAuthController@logout']);
    Route::get('/changePassword', ['as' => 'client.login.edit', 'uses' => 'Auth\ClientAuthController@edit']);
    Route::put('/changePassword', ['as' => 'client.login.update', 'uses' => 'Auth\ClientAuthController@update']);
    Route::resource('/users', 'Client\ClientUserController');
    Route::resource('/businesses', 'Client\ClientBusinessesController');
    Route::resource('/payments', 'Client\ClientPaymentsController');

    Route::resource('/clients', 'ClientsController');
    Route::resource('/features', 'FeaturesController');
    Route::resource('/plans', 'PlansController');
    Route::resource('/categories', 'CategoriesController');
    Route::resource('/fields', 'FieldsController');
    Route::resource('/interests', 'Client\InterestsController');
    Route::get('/handshakes/businesses/{businessId}', [
        'as' => 'client.handshakes.business',
        'uses' => 'Client\HandshakesController@business'
    ]);
    Route::resource('/handshakes', 'Client\HandshakesController');
    Route::get('/inquiries/businesses/{businessId}', [
        'as' => 'client.inquiries.business',
        'uses' => 'Client\InquiryController@business'
    ]);
    Route::resource('/inquiries', 'Client\InquiryController');
    Route::get('/notifications','NotificationController@index');
    Route::get('/notifications/{id}','NotificationController@update');
    Route::get('/notifications/decline/{id}','NotificationController@decline');
});

Route::group(['prefix' => AdminAuthController::ADMIN_URL, 'middleware' => ['admin']], function () {
    Route::get('/', ['as' => 'admin.home', 'uses' => 'AdminPagesController@home']);
    Route::get('/logout', ['as' => 'admin.login.destroy', 'uses' => 'Auth\AdminAuthController@logout']);
    Route::get('/changePassword', ['as' => 'admin.login.edit', 'uses' => 'Auth\AdminAuthController@edit']);
    Route::put('/changePassword', ['as' => 'admin.login.update', 'uses' => 'Auth\AdminAuthController@update']);
    Route::resource('/users', 'UsersController');
    Route::get('/clients/state/{userId}', ['as' => 'manage.clients.state', 'uses' => 'ClientsController@state']);
    Route::resource('/clients', 'ClientsController');
    Route::resource('/features', 'FeaturesController');
    Route::resource('/plans', 'PlansController');
    Route::resource('/categories', 'CategoriesController');
    Route::resource('/fields', 'FieldsController');
    Route::get('/businesses/state/{businessId}', [
        'as' => 'manage.businesses.state',
        'uses' => 'BusinessesController@state'
    ]);
    Route::resource('/businesses', 'BusinessesController');

    Route::resource('/pending', 'PendingBusinessesController');
    Route::resource('/payments', 'PaymentsController');
    Route::get('/newsletter','NewsletterController@index');
    Route::post('/newsletter/email','NewsletterController@email');

});
Route::get('/share/{id}','TestController@index');
Route::post('/email','TestController@sendMail');
Route::get('newuser','NewRegistration@index');
Route::post('newuser/register','NewRegistration@register');
Route::post('upload','TestController@upload');
Route::post('/business/images','TestController@deleteImage');

app/Http/Controllers/Client/ClientBusinessesController.php
<?php

namespace App\Http\Controllers\Client;

use App\Http\Requests\Client\CreateBusinessRequest;
use App\Http\Requests\Client\UpdateBusinessRequest;
use Carbon\Carbon;
use Cartalyst\Sentinel\Laravel\Facades\Sentinel;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use Intervention\Image\Facades\Image;
use SmoDav\Managers\Artist;
use SmoDav\Models\Business;
use SmoDav\Models\BusinessCity;
use SmoDav\Models\BusinessesFieldOfWork;
use SmoDav\Models\BusinessImage;
use SmoDav\Models\Category;
use SmoDav\Models\City;
use SmoDav\Models\Client;
use SmoDav\Models\FieldOfWork;
use SmoDav\Models\Payment;
use SmoDav\Models\PendingChange;
use SmoDav\Models\PendingImageChange;
use SmoDav\Models\Plan;

class ClientBusinessesController extends Controller
{
    /**
     * @var Business
     */
    private $business;
    private $clientId;

    /**
     * BusinessesController constructor.
     *
     * @param Business $business
     */
    public function __construct(Business $business)
    {
        $this->business = $business;
        $this->clientId = session('client_id');
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $businesses = $this->business->where('client_id', $this->clientId)->with(['category'])->get();

        return view('client.businesses.index')
            ->withBusinesses($businesses);
    }

    /**
     * w the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('client.businesses.create')
            ->withCategories(Category::all())
            ->withFields(FieldOfWork::all())
            ->withPlans(Plan::all())
            ->withCities(City::all());
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  CreateBusinessRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateBusinessRequest $request)
    {
        $data = $request->all();
        if (substr($request->website,0,7) === "http://")
        {
            $data['website'] = $request->website;
        }
        elseif (substr($request->website,0,4) === "www.")
        {
            $data['website'] = 'http://'.substr($request->website,4);
        }
        elseif (substr($request->website,0,8) === "https://"){
           $data['website'] = $request->website;
        }
        else{
            $data['website'] = 'http://'.$request->website;
        }
        $data['name'] = ucwords($data['name']);
        $data['client_id'] = $this->clientId;
        $data['logo'] = $this->getLogo($request);
        $data['active'] = 0;
        $data['status'] = Business::STATUS_PENDING;
        $data['slug'] = makeSlug($data['name'], 'slug', $this->business);
        $business = $this->business->create($data);
        $this->getImages($request, $business);
        $this->mapFieldsOfWork($data['field_of_work'], $business->id);
        $this->mapCities($data['city_id'], $business->id);

        Payment::create([
            'business_id' => $business->id,
            'plan_id' => $data['plan_id'],
            'client_id' => $this->clientId,
            'paybill_number' => env('PAYBILL_ACCOUNT'),
            'account_number' => $data['account_number'],
            'amount_paid' => Plan::findOrFail($data['plan_id'])->cost,
            'transaction_number' => $data['transaction_number'],
            'status' => Payment::STATUS_PENDING,
        ]);

        flash('Successfully created new business. Please wait for approval.', 'success');

        return redirect()->route('client.businesses.index');
    }

    private function getLogo(Request $request, $business = null)
    {
        $now = Carbon::now()->timestamp;
        $logo = 'images/default-logo.png';
        if ($business) {
            $logo = $business->logo;
        }

        if ($request->file('logo') && $request->file('logo')->isValid()) {
            $filename = str_random(10) . $now . '.' . $request->file('logo')->getClientOriginalExtension();
            $uploaded = Image::make($request->file('logo'))
                ->resize(280, 280, function ($constraint) {
                    $constraint->aspectRatio();
                });
            $image = Image::canvas(300, 300)
                ->insert($uploaded, 'center');

            $image->save(public_path('images/logos/' . $filename));
            $logo = 'images/logos/' . $filename;

            if ($business && $business->logo != 'images/default-logo.png') {
                unlink(public_path($business->logo));
            }
        }

        return $logo;
    }

    private function mapFieldsOfWork($fieldsOfWork, $businessId)
    {
        $fields = [];
        $timestamp = Carbon::now();
        foreach ($fieldsOfWork as $field) {
            $fields [] = [
                'business_id' => $businessId,
                'field_of_work_id' => $field,
                'created_at' => $timestamp,
                'updated_at' => $timestamp
            ];
        }

        BusinessesFieldOfWork::insert($fields);
    }

    private function mapCities($cities, $businessId)
    {
        $timestamp = Carbon::now();
        $fields = [];
        foreach ($cities as $city) {
            $fields [] = [
                'business_id' => $businessId,
                'city_id' => $city,
                'created_at' => $timestamp,
                'updated_at' => $timestamp
            ];
        }
        BusinessCity::insert($fields);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $businessId
     * @return \Illuminate\Http\Response
     */
    public function show($businessId)
    {
        $business = $this->business->with(['client', 'category','subscriptions.plan', 'fieldsOfWork', 'cities'])
            ->findOrFail($businessId);

        return view('client.businesses.show')
            ->withBusiness($business);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $businessId
     * @return \Illuminate\Http\Response
     */
    public function edit($businessId)
    {
        $business = $this->business->with(['client','subscriptions.plan','images', 'category', 'fieldsOfWork', 'cities'])
            ->findOrFail($businessId);
        $fields = $business->fieldsOfWork;
        $cities = $business->cities;
        $business->fieldsOfWork = $fields->each(function ($item, $key) use ($fields) {
            $fields[$key] = $item->id;
        })->toArray();
        $business->cities = $cities->each(function ($item, $key) use ($cities) {
            $cities[$key] = $item->id;
        })->toArray();

        return view('client.businesses.edit')
            ->withBusiness($business)
            ->withCategories(Category::all())
            ->withFields(FieldOfWork::all())
            ->withPlans(Plan::all())
            ->withCities(City::all());
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  UpdateBusinessRequest  $request
     * @param  int  $businessId
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateBusinessRequest $request, $businessId)
    {
        $business = $this->business
            ->with(['client', 'category', 'fieldsOfWork', 'cities', 'subscriptions'])
            ->findOrFail($businessId);
        $data = $request->all();

        if (substr($request->website,0,7) === "http://")
        {
            $data['website'] = $request->website;
        }
        elseif (substr($request->website,0,4) === "www.")
        {
            $data['website'] = 'http://'.substr($request->website,4);
        }
        elseif (substr($request->website,0,8) === "https://"){
            $data['website'] = $request->website;
        }
        elseif(empty($request->website))
        {
            $data['website'] = '';
        }
        else{
            $data['website'] = 'http://'.$request->website;
        }

        $data['name'] = ucwords($data['name']);
        $data['logo'] = $this->getLogo($request, $business);
        $data['slug'] = makeSlug($data['name'], 'slug', $this->business, true);
        $business->fill($data);
        $pending = PendingChange::find($business->id);
        if (is_null($pending)) {
            $pending = new PendingChange();
        }

        $pending->fill(
            collect($business->toArray())
                ->except(['client', 'category', 'fields_of_work', 'cities', 'subscriptions'])
                ->toArray()
        );
        $pending->save();

        $this->getImages($request, $business, true);
        $this->updateFieldsOfWork($business->fieldsOfWork, $business->id, $data['field_of_work']);
        $this->updateCities($business->cities, $business->id, $data['city_id']);
        flash('Successfully edited business details. Please wait for approval', 'success');

        return redirect()->route('client.businesses.index');
    }

    private function updateFieldsOfWork($fields, $businessId, $selectedFields)
    {
        $businessFields = new BusinessesFieldOfWork();

        $businessFields_id = [];
        foreach ($fields as $field){
            $businessFields_id [] = $field->id;
        }

        BusinessesFieldOfWork::where('business_id',$businessId)->whereIn('field_of_work_id',$businessFields_id)
            ->delete();

        $fields_to_insert = [];
        $timestamp = Carbon::now();
        foreach ($selectedFields as $field) {
            $fields_to_insert [] = [
                'business_id' => $businessId,
                'field_of_work_id' => $field,
                'created_at' => $timestamp,
                'updated_at' => $timestamp
            ];
        }

        $businessFields->insert($fields_to_insert);
    }

    private function updateCities($cities, $businessId, $selectedCities)
    {
        $businessCities = new BusinessCity();

app/Http/Controllers/Client/ClientPagesController.php
<?php

namespace App\Http\Controllers\Client;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use App\Http\Requests;

class ClientPagesController extends Controller
{
    public function home()
    {
        return view('client.pages.dashboard');
    }
}

resources/views/admin/clients/create.blade.php
@extends('admin.layout')
@section('content')
    <section class="content-header">
        <h1>
            Clients
            <small>Manage the clients that are registered in the system.</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{ route('admin.home') }}"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="{{ route('manage.clients.index') }}">Clients</a></li>
            <li class="active">Add Client</li>
        </ol>
    </section>
    <section class="content">
        <div class="box box-solid box-default">
            <div class="box-header with-border">
                <h3 class="box-title">Add new client</h3>
                <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa                  fa-minus"></i></button>
                </div>
            </div>
            <div class="box-body">
                <div class="row">
                    <form action="{{ route('manage.clients.store') }}" role="form" method="post">
                        {{ csrf_field() }}
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="title">Title*</label>
                                <select name="title" id="title" class="form-control">
                                    <option value="Mr." selected="selected">Mr.</option>
                                    <option value="Ms.">Ms.</option>
                                    <option value="Mrs.">Mrs.</option>
                                    <option value="Miss.">Miss.</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="first_name">First Name*</label>
                                <input value="{{ old('first_name') }}" type="text" name="first_name" id="first_name" class="form-control" required>
                            </div>
                            <div class="form-group">
                                <label for="middle_name">Middle Name</label>
                                <input value="{{ old('middle_name') }}" type="text" name="middle_name" id="middle_name" class="form-control" required>
                            </div>
                            <div class="form-group">
                                <label for="last_name">Last Name*</label>
                                <input type="text" name="last_name" id="last_name" class="form-control" required>
                            </div>
                            <div class="form-group">
                                <label for="nationality">Nationality*</label>
                                {{--//form not working on multiple select check tomorrow--}}
                                <select style="width:100%" name="nationality" id="nationality" class="form-control
                            select2" required>
                                    @foreach($nationalities as $nationality)
                                        {{--dd($city)--}}
                                        <option>{{$nationality}}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="gender">Gender*</label>
                                <select name="gender" id="gender" class="form-control">
                                    <option value="M" selected="selected">Male</option>
                                    <option value="F">Female</option>
                                    <option value="U">Undisclosed</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="mobile">Mobile*</label>
                                <input value="{{ old('mobile') }}" name="mobile" id="mobile" type="text" class="form-control" pattern="[0-9]+$" placeholder="254722XXXXXX" required>
                            </div>

                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="identification_type">Identification Type*</label>
                                <select name="identification_type" id="identification_type" class="form-control">
                                    <option value="National ID" selected="selected">National ID</option>
                                    <option value="Passport">Passport</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="identification_number">Identification Number*</label>
                                <input value="{{ old('identification_number') }}" name="identification_number" id="identification_number" type="text" class="form-control" required>
                            </div>
                            <div class="form-group">
                                <label for="email">Email*</label>
                                <input value="{{ old('email') }}" name="email" id="email" type="email" class="form-control" required>
                            </div>
                            <div class="form-group">
                                <label for="country">Country</label>
                                <input value="Kenya" name="country" id="country" type="text" class="form-control" disabled>
                            </div>
                            <div class="form-group">
                                <label for="city">City*</label>
                                {{--//form not working on multiple select check tomorrow--}}
                                <select style="width:100%" name="city" id="city" class="form-control
                            select2" required>
                                    @foreach(\SmoDav\Models\City::all() as $city)
                                        <option>{{$city->name}}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="address1">Address one*</label>
                                <input value="{{ old('address1') }}" name="address1" id="address1" type="text" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="address2">Address two</label>
                                <input value="{{ old('address2') }}" name="address2" id="address2" type="text" class="form-control">
                            </div>
                            <div class="form-group">
                                <label>
                                    <input name="newsletter" type="checkbox" id="newsletter" class="icheck">
                                    I accept receiving promotional emails and newsletter from the mTangaza and its affiliates
                                </label>
                            </div>
                            <div class="form-group">
                                <input type="submit" class="btn btn-primary" value="Create Account">
                                <input type="reset" class="btn btn-danger" value="Clear Form">
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
@endsection
@section('footer')
    <script type="text/javascript">
        $('#title').select2(
                {
                    tags: true,
                    tokenSeparators: [',', ' ']
                }
        );
    </script>
    @endsection

resources/views/admin/clients/index.blade.php
@extends('admin.layout')
@section('content')
<section class="content-header">
    <h1>
        Clients
        <small>Manage the clients that are registered in the system.</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="{{ route('admin.home') }}"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active"><a href="{{ route('manage.clients.index') }}">Clients</a></li>
    </ol>
</section>
<section class="content">
{{--@if(session()->has('client_email'))--}}
    {{--<div class="row">--}}
            {{--<div class="col-sm-8 col-sm-offset-4">--}}
                {{--<div class="box box-solid box-danger">--}}
                    {{--<div class="box-header with-border">--}}
                        {{--<h5 class="box-title">New Client Login Details</h5>--}}
                        {{--<div class="box-tools pull-right">--}}
                            {{--<button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">--}}
                                {{--<i class="fa fa-minus"></i>--}}
                            {{--</button>--}}
                        {{--</div>--}}
                    {{--</div>--}}
                    {{--<div class="box-body">--}}
                        {{--<p>Please note that this will only be displayed once. A copy of the same has been sent to the registered email.</p>--}}
                        {{--<table class="table table-responsive table-condensed table-hover">--}}
                            {{--<tr>--}}
                                {{--<td width="200"><strong>Email</strong></td>--}}
                                {{--<td>{{ session('client_email') }}</td>--}}
                            {{--</tr>--}}
                            {{--<tr>--}}
                                {{--<td><strong>Password</strong></td>--}}
                                {{--<td>{{ session('client_password') }}</td>--}}
                            {{--</tr>--}}
                        {{--</table>--}}
                    {{--</div>--}}
                {{--</div>--}}
            {{--</div>--}}
        {{--</div>--}}
{{--@endif--}}
    <div class="box box-solid box-danger">
        <div class="box-header with-border">
            <h3 class="box-title">Current System Clients</h3>
            <div class="box-tools pull-right">
                <a href="{{ route('manage.clients.create') }}" class="btn btn-xs btn-primary">Add Client</a>
                <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                    <i class="fa fa-minus"></i>
                </button>
            </div>
        </div>
        <div class="box-body">
            <table class="table table-responsive table-condensed table-hover data-table">
                <thead>
                <tr class="success">
                    <th>Email</th>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Mobile</th>
                    <th>User Group</th>
                    <th>Last Login</th>
                    <th>Created At</th>
                    <th></th>
                    <th></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                @foreach($clients as $client)
                    <tr>
                        <td><a href="{{ route('manage.clients.show', $client->id) }}">{{ $client->email }}</a></td>
                        <td>{{ $client->first_name }}</td>
                        <td>{{ $client->last_name }}</td>
                        <td>{{ $client->mobile }}</td>
                        <td>{{ $client->user->roles->first()->name }}</td>
                        <td>{{ is_null($client->user->last_login) ? 'Never' : \Carbon\Carbon::parse($client->user->last_login)->diffForHumans() }}</td>
                        <td>{{ $client->user->created_at->format('d F, Y') }}</td>
                        <td><a class="btn btn-xs btn-info" href="{{ route('manage.clients.edit', $client->id) }}">Edit</a></td>
                        <td><a class="btn btn-xs {{ $client->user->active == 1 ? 'btn-danger' : 'btn-success' }}" href="{{ route('manage.clients.state', $client->user->id) }}">{{ $client->user->active == 1 ? 'Deactivate' : 'Activate' }}</a></td>
                        <td><a class="btn btn-xs btn-danger" href="{{ route('manage.clients.destroy', $client->id) }}" data-method="delete" rel="nofollow" data-confirm="Are you sure you want to delete this?" data-token="{{ csrf_token() }}">Delete</a></td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>

</section>
@endsection