app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

//<script type="text/javascript" src="https://secure.skypeassets.com/i/scom/js/skype-uri.js"></script>
//<div id="SkypeButton_Call_smodav_1">
// <script type="text/javascript">
//    Skype.ui({
// "name": "dropdown",
// "element": "SkypeButton_Call_smodav_1",
// "participants": ["smodav"],
// "imageSize": 24
// });
// </script>
//</div>

use App\Http\Controllers\Auth\AdminAuthController;
use Illuminate\Contracts\Mail\Mailer;
use Illuminate\Http\Request;
use SmoDav\Models\Business;

Route::get('/', function () {
    return view('welcome');
});
Route::get('api/search', 'SearchController@getResults');
Route::get('api/search/businesses', 'SearchController@getBusinesses');
Route::get('api/search/business', 'SearchController@getBusinessBySlug');
Route::get('api/search/fieldBusinesses', 'SearchController@getFieldBusinessesBySlug');
Route::get('api/search/fields', 'SearchController@getFields');
Route::get('api/featured', 'SearchController@getFeatured');
Route::get('api/refresh', 'SearchController@refreshIndex');
Route::post('api/inquiry', function (Request $request, Mailer $mailer) {
    $data = $request->all();
    $business = Business::whereSlug($data['slug'])->first();

    $mailer->send('emails.contact', ['data' => $data], function ($message) use ($data, $business) {
        $message
            ->from($data['email'], $data['name'])
            ->to($business->email)
            ->subject('Inquiry from Contact Form' . $data['subject']);
    });

    return 'success';
});

Route::post('api/contact', function (Request $request, Mailer $mailer) {
    $data = $request->all();
    $mailer->send('emails.contact', ['data' => $data], function ($message) use ($data) {
        $message
            ->from($data['email'], $data['name'])
            ->to('info@mtangaza.com')
            ->subject('Inquiry from Contact Form' . $data['subject']);
    });
    return 'success';
});

Route::group(['middleware' => ['guest']], function () {
    $admin = AdminAuthController::ADMIN_URL;
    Route::get($admin . '/login', ['as' => 'admin.login.index', 'uses' => 'Auth\AdminAuthController@getLogin']);
    Route::post($admin . '/login', ['as' => 'admin.login.store', 'uses' => 'Auth\AdminAuthController@postLogin']);
    Route::get('client/login', ['as' => 'client.login.index', 'uses' => 'Auth\ClientAuthController@getLogin']);
    Route::post('client/login', ['as' => 'client.login.store', 'uses' => 'Auth\ClientAuthController@postLogin']);
});

Route::group(['prefix' => 'client', 'middleware' => ['client']], function () {
    Route::get('/', ['as' => 'client.home', 'uses' => 'Client\ClientPagesController@home']);
    Route::get('/logout', ['as' => 'client.login.destroy', 'uses' => 'Auth\ClientAuthController@logout']);
    Route::get('/changePassword', ['as' => 'client.login.edit', 'uses' => 'Auth\ClientAuthController@edit']);
    Route::put('/changePassword', ['as' => 'client.login.update', 'uses' => 'Auth\ClientAuthController@update']);
    Route::resource('/users', 'Client\ClientUserController');
    Route::resource('/businesses', 'Client\ClientBusinessesController');
    Route::resource('/payments', 'Client\ClientPaymentsController');

    Route::resource('/clients', 'ClientsController');
    Route::resource('/features', 'FeaturesController');
    Route::resource('/plans', 'PlansController');
    Route::resource('/categories', 'CategoriesController');
    Route::resource('/fields', 'FieldsController');
    Route::resource('/interests', 'Client\InterestsController');
    Route::get('/handshakes/businesses/{businessId}', [
        'as' => 'client.handshakes.business',
        'uses' => 'Client\HandshakesController@business'
    ]);
    Route::resource('/handshakes', 'Client\HandshakesController');
    Route::get('/inquiries/businesses/{businessId}', [
        'as' => 'client.inquiries.business',
        'uses' => 'Client\InquiryController@business'
    ]);
    Route::resource('/inquiries', 'Client\InquiryController');
    Route::get('/notifications','NotificationController@index');
    Route::get('/notifications/{id}','NotificationController@update');
    Route::get('/notifications/decline/{id}','NotificationController@decline');
});

Route::group(['prefix' => AdminAuthController::ADMIN_URL, 'middleware' => ['admin']], function () {
    Route::get('/', ['as' => 'admin.home', 'uses' => 'AdminPagesController@home']);
    Route::get('/logout', ['as' => 'admin.login.destroy', 'uses' => 'Auth\AdminAuthController@logout']);
    Route::get('/changePassword', ['as' => 'admin.login.edit', 'uses' => 'Auth\AdminAuthController@edit']);
    Route::put('/changePassword', ['as' => 'admin.login.update', 'uses' => 'Auth\AdminAuthController@update']);
    Route::resource('/users', 'UsersController');
    Route::get('/clients/state/{userId}', ['as' => 'manage.clients.state', 'uses' => 'ClientsController@state']);
    Route::resource('/clients', 'ClientsController');
    Route::resource('/features', 'FeaturesController');
    Route::resource('/plans', 'PlansController');
    Route::resource('/categories', 'CategoriesController');
    Route::resource('/fields', 'FieldsController');
    Route::get('/businesses/state/{businessId}', [
        'as' => 'manage.businesses.state',
        'uses' => 'BusinessesController@state'
    ]);
    Route::resource('/businesses', 'BusinessesController');

    Route::resource('/pending', 'PendingBusinessesController');
    Route::resource('/payments', 'PaymentsController');
    Route::get('/newsletter','NewsletterController@index');
    Route::post('/newsletter/email','NewsletterController@email');

});
Route::get('/share/{id}','TestController@index');
Route::post('/email','TestController@sendMail');
Route::get('newuser','NewRegistration@index');
Route::post('newuser/register','NewRegistration@register');
Route::post('upload','TestController@upload');
Route::post('/business/images','TestController@deleteImage');

app/Http/Controllers/Client/ClientBusinessesController.php
<?php

namespace App\Http\Controllers\Client;

use App\Http\Requests\Client\CreateBusinessRequest;
use App\Http\Requests\Client\UpdateBusinessRequest;
use Carbon\Carbon;
use Cartalyst\Sentinel\Laravel\Facades\Sentinel;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use Intervention\Image\Facades\Image;
use SmoDav\Managers\Artist;
use SmoDav\Models\Business;
use SmoDav\Models\BusinessCity;
use SmoDav\Models\BusinessesFieldOfWork;
use SmoDav\Models\BusinessImage;
use SmoDav\Models\Category;
use SmoDav\Models\City;
use SmoDav\Models\Client;
use SmoDav\Models\FieldOfWork;
use SmoDav\Models\Payment;
use SmoDav\Models\PendingChange;
use SmoDav\Models\PendingImageChange;
use SmoDav\Models\Plan;

class ClientBusinessesController extends Controller
{
    /**
     * @var Business
     */
    private $business;
    private $clientId;

    /**
     * BusinessesController constructor.
     *
     * @param Business $business
     */
    public function __construct(Business $business)
    {
        $this->business = $business;
        $this->clientId = session('client_id');
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $businesses = $this->business->where('client_id', $this->clientId)->with(['category'])->get();

        return view('client.businesses.index')
            ->withBusinesses($businesses);
    }

    /**
     * w the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('client.businesses.create')
            ->withCategories(Category::all())
            ->withFields(FieldOfWork::all())
            ->withPlans(Plan::all())
            ->withCities(City::all());
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  CreateBusinessRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateBusinessRequest $request)
    {
        $data = $request->all();
        if (substr($request->website,0,7) === "http://")
        {
            $data['website'] = $request->website;
        }
        elseif (substr($request->website,0,4) === "www.")
        {
            $data['website'] = 'http://'.substr($request->website,4);
        }
        elseif (substr($request->website,0,8) === "https://"){
           $data['website'] = $request->website;
        }
        else{
            $data['website'] = 'http://'.$request->website;
        }
        $data['name'] = ucwords($data['name']);
        $data['client_id'] = $this->clientId;
        $data['logo'] = $this->getLogo($request);
        $data['active'] = 0;
        $data['status'] = Business::STATUS_PENDING;
        $data['slug'] = makeSlug($data['name'], 'slug', $this->business);
        $business = $this->business->create($data);
        $this->getImages($request, $business);
        $this->mapFieldsOfWork($data['field_of_work'], $business->id);
        $this->mapCities($data['city_id'], $business->id);

        Payment::create([
            'business_id' => $business->id,
            'plan_id' => $data['plan_id'],
            'client_id' => $this->clientId,
            'paybill_number' => env('PAYBILL_ACCOUNT'),
            'account_number' => $data['account_number'],
            'amount_paid' => Plan::findOrFail($data['plan_id'])->cost,
            'transaction_number' => $data['transaction_number'],
            'status' => Payment::STATUS_PENDING,
        ]);

        flash('Successfully created new business. Please wait for approval.', 'success');

        return redirect()->route('client.businesses.index');
    }

    private function getLogo(Request $request, $business = null)
    {
        $now = Carbon::now()->timestamp;
        $logo = 'images/default-logo.png';
        if ($business) {
            $logo = $business->logo;
        }

        if ($request->file('logo') && $request->file('logo')->isValid()) {
            $filename = str_random(10) . $now . '.' . $request->file('logo')->getClientOriginalExtension();
            $uploaded = Image::make($request->file('logo'))
                ->resize(280, 280, function ($constraint) {
                    $constraint->aspectRatio();
                });
            $image = Image::canvas(300, 300)
                ->insert($uploaded, 'center');

            $image->save(public_path('images/logos/' . $filename));
            $logo = 'images/logos/' . $filename;

            if ($business && $business->logo != 'images/default-logo.png') {
                unlink(public_path($business->logo));
            }
        }

        return $logo;
    }

    private function mapFieldsOfWork($fieldsOfWork, $businessId)
    {
        $fields = [];
        $timestamp = Carbon::now();
        foreach ($fieldsOfWork as $field) {
            $fields [] = [
                'business_id' => $businessId,
                'field_of_work_id' => $field,
                'created_at' => $timestamp,
                'updated_at' => $timestamp
            ];
        }

        BusinessesFieldOfWork::insert($fields);
    }

    private function mapCities($cities, $businessId)
    {
        $timestamp = Carbon::now();
        $fields = [];
        foreach ($cities as $city) {
            $fields [] = [
                'business_id' => $businessId,
                'city_id' => $city,
                'created_at' => $timestamp,
                'updated_at' => $timestamp
            ];
        }
        BusinessCity::insert($fields);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $businessId
     * @return \Illuminate\Http\Response
     */
    public function show($businessId)
    {
        $business = $this->business->with(['client', 'category','subscriptions.plan', 'fieldsOfWork', 'cities'])
            ->findOrFail($businessId);

        return view('client.businesses.show')
            ->withBusiness($business);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $businessId
     * @return \Illuminate\Http\Response
     */
    public function edit($businessId)
    {
        $business = $this->business->with(['client','subscriptions.plan','images', 'category', 'fieldsOfWork', 'cities'])
            ->findOrFail($businessId);
        $fields = $business->fieldsOfWork;
        $cities = $business->cities;
        $business->fieldsOfWork = $fields->each(function ($item, $key) use ($fields) {
            $fields[$key] = $item->id;
        })->toArray();
        $business->cities = $cities->each(function ($item, $key) use ($cities) {
            $cities[$key] = $item->id;
        })->toArray();

        return view('client.businesses.edit')
            ->withBusiness($business)
            ->withCategories(Category::all())
            ->withFields(FieldOfWork::all())
            ->withPlans(Plan::all())
            ->withCities(City::all());
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  UpdateBusinessRequest  $request
     * @param  int  $businessId
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateBusinessRequest $request, $businessId)
    {
        $business = $this->business
            ->with(['client', 'category', 'fieldsOfWork', 'cities', 'subscriptions'])
            ->findOrFail($businessId);
        $data = $request->all();

        if (substr($request->website,0,7) === "http://")
        {
            $data['website'] = $request->website;
        }
        elseif (substr($request->website,0,4) === "www.")
        {
            $data['website'] = 'http://'.substr($request->website,4);
        }
        elseif (substr($request->website,0,8) === "https://"){
            $data['website'] = $request->website;
        }
        elseif(empty($request->website))
        {
            $data['website'] = '';
        }
        else{
            $data['website'] = 'http://'.$request->website;
        }

        $data['name'] = ucwords($data['name']);
        $data['logo'] = $this->getLogo($request, $business);
        $data['slug'] = makeSlug($data['name'], 'slug', $this->business, true);
        $business->fill($data);
        $pending = PendingChange::find($business->id);
        if (is_null($pending)) {
            $pending = new PendingChange();
        }

        $pending->fill(
            collect($business->toArray())
                ->except(['client', 'category', 'fields_of_work', 'cities', 'subscriptions'])
                ->toArray()
        );
        $pending->save();

        $this->getImages($request, $business, true);
        $this->updateFieldsOfWork($business->fieldsOfWork, $business->id, $data['field_of_work']);
        $this->updateCities($business->cities, $business->id, $data['city_id']);
        flash('Successfully edited business details. Please wait for approval', 'success');

        return redirect()->route('client.businesses.index');
    }

    private function updateFieldsOfWork($fields, $businessId, $selectedFields)
    {
        $businessFields = new BusinessesFieldOfWork();

        $businessFields_id = [];
        foreach ($fields as $field){
            $businessFields_id [] = $field->id;
        }

        BusinessesFieldOfWork::where('business_id',$businessId)->whereIn('field_of_work_id',$businessFields_id)
            ->delete();

        $fields_to_insert = [];
        $timestamp = Carbon::now();
        foreach ($selectedFields as $field) {
            $fields_to_insert [] = [
                'business_id' => $businessId,
                'field_of_work_id' => $field,
                'created_at' => $timestamp,
                'updated_at' => $timestamp
            ];
        }

        $businessFields->insert($fields_to_insert);
    }

    private function updateCities($cities, $businessId, $selectedCities)
    {
        $businessCities = new BusinessCity();

app/Http/Controllers/Client/ClientPagesController.php
<?php

namespace App\Http\Controllers\Client;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use App\Http\Requests;

class ClientPagesController extends Controller
{
    public function home()
    {
        return view('client.pages.dashboard');
    }
}

resources/views/client/partials/footer.blade.php
<footer class="main-footer">
    <div class="pull-right hidden-xs">
        {{--<b>Version</b> 1.0.0--}}
    </div>
    <strong>Copyright &copy; {{ \Carbon\Carbon::now()->year }} <a href="http://wizag.biz">Wise & Agile Solutions Limited</a>.</strong> All rights
    reserved.
</footer>

resources/views/client/partials/header.blade.php
<header class="main-header">
    <!-- Logo -->
    <a href="{{ route('client.home') }}" class="logo">
        <span class="logo-mini"><b>m</b>T</span>
            <span class="logo-lg">
                <img src="{{ asset('images/top-logo.png') }}" alt="mTangaza" class="img-responsive">
            </span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </a>

        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <!-- Notifications: style can be found in dropdown.less -->
                {{--<li class="dropdown notifications-menu">--}}
                    {{--<a href="#" class="dropdown-toggle" data-toggle="dropdown">--}}
                        {{--<i class="fa fa-bell-o"></i>--}}
                        {{--<span class="label label-warning">10</span>--}}
                    {{--</a>--}}
                    {{--<ul class="dropdown-menu">--}}
                        {{--<li class="header">You have 10 notifications</li>--}}
                        {{--<li>--}}
                            {{--<ul class="menu">--}}
                                {{--<li>--}}
                                    {{--<a href="#">--}}
                                        {{--<i class="fa fa-users text-aqua"></i> 5 new members joined today--}}
                                    {{--</a>--}}
                                {{--</li>--}}
                            {{--</ul>--}}
                        {{--</li>--}}
                        {{--<li class="footer"><a href="#">View all</a></li>--}}
                    {{--</ul>--}}
                {{--</li>--}}

                <li class="dropdown user user-menu">
                    <a href="#" class="btn btn-success dropdown-toggle" data-toggle="dropdown">
                        Notifications <span class="badge">{{ count($notifications) }}</span>
                    </a>
                    <ul class="dropdown-menu">
                        <li >

                                <h5 style="margin-left: 5px">{{$user->name}} you have {{ count($notifications) }} notifications pending</h5>

                        </li>
                        <li class="user-footer">
                            {{--<div class="pull-left">--}}
                                {{--<a href="{{ route('client.login.edit') }}" class="btn btn-default btn-flat">Change Password</a>--}}
                            {{--</div>--}}
                            <div class="pull-right">
                                <a href="{{url('client/notifications')}}" class="btn btn-default btn-flat">View</a>
                            </div>
                        </li>
                    </ul>
                </li>
                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
{{--                        <img src="{{ asset('images/top-logo.png') }}" class="user-image" alt="User Image">--}}
                        <span class="hidden-xs">{{ $user->email }}</span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="user-header">
                            <p>
                                {{ $user->email }}
                                <small>Last Login: {{ \Carbon\Carbon::parse($user->last_login)->format('d F Y') }}</small>
                            </p>
                        </li>
                        <li class="user-footer">
                            <div class="pull-left">
                                <a href="{{ route('client.login.edit') }}" class="btn btn-default btn-flat">Change Password</a>
                            </div>
                            <div class="pull-right">
                                <a href="{{ route('client.login.destroy') }}" class="btn btn-default btn-flat">Sign out</a>
                            </div>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
</header>

resources/views/client/partials/sidebar.blade.php
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search...">
              <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                </button>
              </span>
            </div>
        </form>
        <!-- /.search form -->

        <ul class="sidebar-menu">
            <li>
                <a href="{{ route('client.home') }}">
                    <i class="fa fa-dashboard"></i> <span>Dashboard</span>
                </a>
            </li>
            <li class="header">Your Resources</li>
            <li>
                <a href="{{ route('client.users.index') }}">
                    <i class="fa fa-users"></i> <span>Authorised Users</span>
                </a>
            </li>
            <li>
                <a href="{{ route('client.businesses.index') }}">
                    <i class="fa fa-suitcase"></i> <span>Businesses</span>
                </a>
            </li>
            <li>
                <a href="{{ route('client.payments.index') }}">
                    <i class="fa fa-money"></i> <span>Payments</span>
                </a>
            </li>
            @if(\SmoDav\Models\Business::where('client_id',session('client_id'))->get()->count() > 0)
            <li>
                <a href="#">
                    <i class="fa fa-file-o"></i>
                    <span data-toggle="modal" data-target="#sideUpload">
                        Uploads</span>
                </a>
            </li>
            @endif
            <li class="header">Your Relations</li>
            <li>
                <a href="{{ route('client.interests.index') }}">
                    <i class="fa fa-link"></i> <span>Interests</span>
                </a>
            </li>
            <li>
                <a href="{{ route('client.handshakes.index') }}">
                    <i class="fa fa-users"></i> <span>Handshakes</span>
                </a>
            </li>
            <li>
                <a href="{{ route('client.inquiries.index') }}">
                    <i class="fa fa-envelope"></i> <span>Inquiries</span>
                </a>
            </li>
        </ul>
    </section>
    <!-- /.sidebar -->
</aside>

<!--share model -->
<div class="modal fade" id="sideUpload" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                <h4 class="modal-title text-center" id="myModalLabel">Upload Business Document</h4>
            </div>
            <div class="modal-body">
                <div class="text-content">
                    <div class="span7 offset1">{!! Form::open(
    array(
        'url' => 'upload',
        'class' => 'form',
        'novalidate' => 'novalidate',
        'enctype'=>'multipart/form-data',
        'files' => true)) !!}

                        <div class="input-group">
                            <span class="input-group-addon" id="basic-addon1">Document name</span>
                            {!! Form::text('name', null, array(null=>'Enter document name','required','placeholder'=>'Eg Price list',
                            'required'=>'required','class'=>'form-control','aria-describedby'=>'basic-addon1')) !!}
                        </div>

                        <div style="margin-top: 5px" class="panel panel-default">
                            {!! Form::label('Select file,') !!}<span>The file will be available to businesses that
                                follow you and those you follow</span>
                            <div class="panel-body">
                                {!! Form::file('doc', null) !!}
                            </div>
                        </div>

                        <div style="margin-top: 5px" class="panel panel-default">
                            <h5>Select the business for which you want to upload the file</h5>

                            <div class="panel-body form-group">

                                {{--//form not working on multiple select check tomorrow--}}
                                <select style="width:100%" required="required" name="selected[]" id="selected" class="form-control
                            select2" multiple>

                                    @foreach(\SmoDav\Models\Business::where('client_id',session('client_id'))->get() as $busines)
                                        <option {{ in_array([$busines->id], [$busines->name]) ? 'selected' : '' }} value="{{
                                     $busines->id }}">{{ $busines->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>

                        <div class="row col-md-12">
                            <div class=" pull-right">

                                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>

                                {!! Form::submit('Upload',array('class'=>'btn btn-primary')) !!}

                            </div>
                        </div>

                    </div>

                </div>
            </div>
            <div class="modal-footer">
                {{--<button type="button" class="btn btn-primary">Share document</button>--}}
            </div>
            {!! Form::close() !!}
        </div>
    </div>
</div>