app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

//<script type="text/javascript" src="https://secure.skypeassets.com/i/scom/js/skype-uri.js"></script>
//<div id="SkypeButton_Call_smodav_1">
// <script type="text/javascript">
//    Skype.ui({
// "name": "dropdown",
// "element": "SkypeButton_Call_smodav_1",
// "participants": ["smodav"],
// "imageSize": 24
// });
// </script>
//</div>

use App\Http\Controllers\Auth\AdminAuthController;
use Illuminate\Contracts\Mail\Mailer;
use Illuminate\Http\Request;
use SmoDav\Models\Business;

Route::get('/', function () {
    return view('welcome');
});
Route::get('api/search', 'SearchController@getResults');
Route::get('api/search/businesses', 'SearchController@getBusinesses');
Route::get('api/search/business', 'SearchController@getBusinessBySlug');
Route::get('api/search/fieldBusinesses', 'SearchController@getFieldBusinessesBySlug');
Route::get('api/search/fields', 'SearchController@getFields');
Route::get('api/featured', 'SearchController@getFeatured');
Route::get('api/refresh', 'SearchController@refreshIndex');
Route::post('api/inquiry', function (Request $request, Mailer $mailer) {
    $data = $request->all();
    $business = Business::whereSlug($data['slug'])->first();

    $mailer->send('emails.contact', ['data' => $data], function ($message) use ($data, $business) {
        $message
            ->from($data['email'], $data['name'])
            ->to($business->email)
            ->subject('Inquiry from Contact Form' . $data['subject']);
    });

    return 'success';
});

Route::post('api/contact', function (Request $request, Mailer $mailer) {
    $data = $request->all();
    $mailer->send('emails.contact', ['data' => $data], function ($message) use ($data) {
        $message
            ->from($data['email'], $data['name'])
            ->to('info@mtangaza.com')
            ->subject('Inquiry from Contact Form' . $data['subject']);
    });
    return 'success';
});

Route::group(['middleware' => ['guest']], function () {
    $admin = AdminAuthController::ADMIN_URL;
    Route::get($admin . '/login', ['as' => 'admin.login.index', 'uses' => 'Auth\AdminAuthController@getLogin']);
    Route::post($admin . '/login', ['as' => 'admin.login.store', 'uses' => 'Auth\AdminAuthController@postLogin']);
    Route::get('client/login', ['as' => 'client.login.index', 'uses' => 'Auth\ClientAuthController@getLogin']);
    Route::post('client/login', ['as' => 'client.login.store', 'uses' => 'Auth\ClientAuthController@postLogin']);
});

Route::group(['prefix' => 'client', 'middleware' => ['client']], function () {
    Route::get('/', ['as' => 'client.home', 'uses' => 'Client\ClientPagesController@home']);
    Route::get('/logout', ['as' => 'client.login.destroy', 'uses' => 'Auth\ClientAuthController@logout']);
    Route::get('/changePassword', ['as' => 'client.login.edit', 'uses' => 'Auth\ClientAuthController@edit']);
    Route::put('/changePassword', ['as' => 'client.login.update', 'uses' => 'Auth\ClientAuthController@update']);
    Route::resource('/users', 'Client\ClientUserController');
    Route::resource('/businesses', 'Client\ClientBusinessesController');
    Route::resource('/payments', 'Client\ClientPaymentsController');

    Route::resource('/clients', 'ClientsController');
    Route::resource('/features', 'FeaturesController');
    Route::resource('/plans', 'PlansController');
    Route::resource('/categories', 'CategoriesController');
    Route::resource('/fields', 'FieldsController');
    Route::resource('/interests', 'Client\InterestsController');
    Route::get('/handshakes/businesses/{businessId}', [
        'as' => 'client.handshakes.business',
        'uses' => 'Client\HandshakesController@business'
    ]);
    Route::resource('/handshakes', 'Client\HandshakesController');
    Route::get('/inquiries/businesses/{businessId}', [
        'as' => 'client.inquiries.business',
        'uses' => 'Client\InquiryController@business'
    ]);
    Route::resource('/inquiries', 'Client\InquiryController');
    Route::get('/notifications','NotificationController@index');
    Route::get('/notifications/{id}','NotificationController@update');
    Route::get('/notifications/decline/{id}','NotificationController@decline');
});

Route::group(['prefix' => AdminAuthController::ADMIN_URL, 'middleware' => ['admin']], function () {
    Route::get('/', ['as' => 'admin.home', 'uses' => 'AdminPagesController@home']);
    Route::get('/logout', ['as' => 'admin.login.destroy', 'uses' => 'Auth\AdminAuthController@logout']);
    Route::get('/changePassword', ['as' => 'admin.login.edit', 'uses' => 'Auth\AdminAuthController@edit']);
    Route::put('/changePassword', ['as' => 'admin.login.update', 'uses' => 'Auth\AdminAuthController@update']);
    Route::resource('/users', 'UsersController');
    Route::get('/clients/state/{userId}', ['as' => 'manage.clients.state', 'uses' => 'ClientsController@state']);
    Route::resource('/clients', 'ClientsController');
    Route::resource('/features', 'FeaturesController');
    Route::resource('/plans', 'PlansController');
    Route::resource('/categories', 'CategoriesController');
    Route::resource('/fields', 'FieldsController');
    Route::get('/businesses/state/{businessId}', [
        'as' => 'manage.businesses.state',
        'uses' => 'BusinessesController@state'
    ]);
    Route::resource('/businesses', 'BusinessesController');

    Route::resource('/pending', 'PendingBusinessesController');
    Route::resource('/payments', 'PaymentsController');
    Route::get('/newsletter','NewsletterController@index');
    Route::post('/newsletter/email','NewsletterController@email');

});
Route::get('/share/{id}','TestController@index');
Route::post('/email','TestController@sendMail');
Route::get('newuser','NewRegistration@index');
Route::post('newuser/register','NewRegistration@register');
Route::post('upload','TestController@upload');
Route::post('/business/images','TestController@deleteImage');

app/Http/Controllers/CategoriesController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Categories\CreateCategoryRequest;
use App\Http\Requests\Categories\DeleteCategoryRequest;
use App\Http\Requests\Categories\EditCategoryRequest;
use Illuminate\Http\Request;

use App\Http\Requests;
use SmoDav\Models\Category;

class CategoriesController extends Controller
{
    /**
     * @var Category
     */
    private $category;

    /**
     * CategoriesController constructor.
     *
     * @param Category $category
     */
    public function __construct(Category $category)
    {
        $this->category = $category;
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.categories.index')
            ->withCategories($this->category->all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @param CreateCategoryRequest $request
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateCategoryRequest $request)
    {
        $data = $request->all();
        $data['slug'] = makeSlug($data['name'], 'name', $this->category);
        $this->category->create($data);
        flash('Successfully created new category', 'success');

        return redirect()->route('manage.categories.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $categoryId
     *
     * @return \Illuminate\Http\Response
     */
    public function edit($categoryId)
    {
        $category = $this->category->findOrFail($categoryId);

        return view('admin.categories.edit')->withCategory($category);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  EditCategoryRequest  $request
     * @param  int  $categoryId
     * @return \Illuminate\Http\Response
     */
    public function update(EditCategoryRequest $request, $categoryId)
    {
        $category = $this->category->findOrFail($categoryId);
        $data = $request->all();
        $data['slug'] = makeSlug($data['name'], 'name', $this->category, true);
        $category->fill($data);
        $category->save();
        flash('Successfully edited category', 'success');

        return redirect()->route('manage.categories.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $categoryId
     * @param DeleteCategoryRequest $request
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy($categoryId, DeleteCategoryRequest $request)
    {
        $category = $this->category->findOrFail($categoryId);

        // TODO: check for mapped categories
        $category->delete();
        flash('Successfully deleted category', 'success');

        return redirect()->route('manage.categories.index');
    }
}

resources/views/admin/categories/create.blade.php
@extends('admin.layout')
@section('content')
    <section class="content-header">
        <h1>
            Categories
            <small>Manage the categories that are registered in the system.</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{ route('admin.home') }}"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="{{ route('manage.categories.index') }}">Categories</a></li>
            <li class="active"><a href="#">Create</a></li>
        </ol>
    </section>
    <section class="content">
        <div class="box box-solid box-default">
            <div class="box-header with-border">
                <h3 class="box-title">Add new category</h3>
                <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                </div>
            </div>
            <div class="box-body">
                <div class="row">
                    <form action="{{ route('manage.categories.store') }}" role="form" method="post">
                        {{ csrf_field() }}
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="name">Category Name*</label>
                                <input value="{{ old('name') }}" type="text" name="name" id="name" class="form-control" required>
                            </div>
                            <div class="form-group">
                                <input type="submit" class="btn btn-primary" value="Create Category">
                                <input type="reset" class="btn btn-danger" value="Clear Form">
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/admin/categories/edit.blade.php
@extends('admin.layout')
@section('content')
    <section class="content-header">
        <h1>
            Categories
            <small>Manage the categories that are registered in the system.</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{ route('admin.home') }}"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="{{ route('manage.categories.index') }}">Categories</a></li>
            <li class="active"><a href="#">Edit</a></li>
        </ol>
    </section>
    <section class="content">
        <div class="box box-solid box-default">
            <div class="box-header with-border">
                <h3 class="box-title">Edit category</h3>
                <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                </div>
            </div>
            <div class="box-body">
                <div class="row">
                    <form action="{{ route('manage.categories.update', $category->id) }}" role="form" method="post">
                        {{ csrf_field() }}
                        {{ method_field('put') }}
                        <input type="hidden" name="categoryId" value="{{ $category->id }}">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="name">Category Name*</label>
                                <input value="{{ $category->name }}" type="text" name="name" id="name" class="form-control" required>
                            </div>
                            <div class="form-group">
                                <input type="submit" class="btn btn-primary" value="Save Changes">
                                <input type="reset" class="btn btn-danger" value="Clear Form">
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/admin/categories/index.blade.php
@extends('admin.layout')
@section('content')
<section class="content-header">
    <h1>
        Categories
        <small>Manage the categories that are registered in the system.</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="{{ route('admin.home') }}"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active"><a href="{{ route('manage.categories.index') }}">Categories</a></li>
    </ol>
</section>
<section class="content">
    <div class="box box-solid box-danger">
        <div class="box-header with-border">
            <h3 class="box-title">Current Setup Categories</h3>
            <div class="box-tools pull-right">
                <a href="{{ route('manage.categories.create') }}" class="btn btn-xs btn-primary">Add Category</a>
                <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                    <i class="fa fa-minus"></i>
                </button>
            </div>
        </div>
        <div class="box-body">
            <table class="table table-responsive table-condensed table-hover data-table">
                <thead>
                <tr class="success">
                    <th>Category Name</th>
                    <th>Created At</th>
                    <th>Updated At</th>
                    <th></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                @foreach($categories as $category)
                    <tr>
                        <td><a href="{{ route('manage.categories.show', $category->id) }}">{{ $category->name }}</a></td>
                        <td>{{ $category->created_at->format('d F Y') }}</td>
                        <td>{{ $category->updated_at->format('d F Y') }}</td>
                        <td><a class="btn btn-xs btn-info" href="{{ route('manage.categories.edit', $category->id) }}">Edit</a></td>
                        <td><a class="btn btn-xs btn-danger" href="{{ route('manage.categories.destroy', $category->id) }}" data-method="delete" rel="nofollow" data-confirm="Are you sure you want to delete this?" data-token="{{ csrf_token() }}">Delete</a></td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>

</section>
@endsection

resources/views/admin/categories/show.blade.php
@extends('admin.layout')
@section('content')
    <section class="content-header">
        <h1>
            Clients
            <small>Manage the clients that are registered in the system.</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{ route('admin.home') }}"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="{{ route('manage.clients.index') }}">Clients</a></li>
            <li class="active">View Client Details</li>
        </ol>
    </section>
    <section class="content">
        <div class="box box-solid box-default">
            <div class="box-header with-border">
                <h3 class="box-title">{{ $client->first_name . ' ' . $client->last_name }} details</h3>
                <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                </div>
            </div>
            <div class="box-body">
                <div class="container">
                    <div class="row">
                        <div class="col-md-6">
                            <hr>
                            <span class="display-label">Title:</span>
                            <span><strong>{{ $client->title }}</strong></span>
                            <hr>
                            <span class="display-label">First Name:</span>
                            <span><strong>{{ $client->first_name }}</strong></span>
                            <hr>
                            <span class="display-label">Last Name:</span>
                            <span><strong>{{ $client->last_name }}</strong></span>
                            <hr>
                            <span class="display-label">Nationality:</span>
                            <span><strong>{{ $client->nationality }}</strong></span>
                            <hr>
                            <span class="display-label">Gender:</span>
                            <span><strong>{{ $client->gender == 'M' ? 'Male' : 'Female' }}</strong></span>
                            <hr>
                        </div>
                        <div class="col-md-6">
                            <hr>
                            <span class="display-label">{{ $client->identification_type }}:</span>
                            <span><strong>{{ $client->identification_number }}</strong></span>
                            <hr>
                            <span class="display-label">Email:</span>
                            <span><strong>{{ $client->email }}</strong></span>
                            <hr>
                            <span class="display-label">Mobile:</span>
                            <span><strong>{{ $client->mobile }}</strong></span>
                            <hr>
                            <span class="display-label">Address:</span>
                            <span><strong>{{ $client->address }}</strong></span>
                            <hr>
                            <div class="form-group">
                                <a href="{{ route('manage.clients.edit', $client->id) }}" class="btn btn-primary">Edit Account</a>
                                <a href="{{ URL::previous() }}" class="btn btn-danger">Back</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection