app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

//<script type="text/javascript" src="https://secure.skypeassets.com/i/scom/js/skype-uri.js"></script>
//<div id="SkypeButton_Call_smodav_1">
// <script type="text/javascript">
//    Skype.ui({
// "name": "dropdown",
// "element": "SkypeButton_Call_smodav_1",
// "participants": ["smodav"],
// "imageSize": 24
// });
// </script>
//</div>

use App\Http\Controllers\Auth\AdminAuthController;
use Illuminate\Contracts\Mail\Mailer;
use Illuminate\Http\Request;
use SmoDav\Models\Business;

Route::get('/', function () {
    return view('welcome');
});
Route::get('api/search', 'SearchController@getResults');
Route::get('api/search/businesses', 'SearchController@getBusinesses');
Route::get('api/search/business', 'SearchController@getBusinessBySlug');
Route::get('api/search/fieldBusinesses', 'SearchController@getFieldBusinessesBySlug');
Route::get('api/search/fields', 'SearchController@getFields');
Route::get('api/featured', 'SearchController@getFeatured');
Route::get('api/refresh', 'SearchController@refreshIndex');
Route::post('api/inquiry', function (Request $request, Mailer $mailer) {
    $data = $request->all();
    $business = Business::whereSlug($data['slug'])->first();

    $mailer->send('emails.contact', ['data' => $data], function ($message) use ($data, $business) {
        $message
            ->from($data['email'], $data['name'])
            ->to($business->email)
            ->subject('Inquiry from Contact Form' . $data['subject']);
    });

    return 'success';
});

Route::post('api/contact', function (Request $request, Mailer $mailer) {
    $data = $request->all();
    $mailer->send('emails.contact', ['data' => $data], function ($message) use ($data) {
        $message
            ->from($data['email'], $data['name'])
            ->to('info@mtangaza.com')
            ->subject('Inquiry from Contact Form' . $data['subject']);
    });
    return 'success';
});

Route::group(['middleware' => ['guest']], function () {
    $admin = AdminAuthController::ADMIN_URL;
    Route::get($admin . '/login', ['as' => 'admin.login.index', 'uses' => 'Auth\AdminAuthController@getLogin']);
    Route::post($admin . '/login', ['as' => 'admin.login.store', 'uses' => 'Auth\AdminAuthController@postLogin']);
    Route::get('client/login', ['as' => 'client.login.index', 'uses' => 'Auth\ClientAuthController@getLogin']);
    Route::post('client/login', ['as' => 'client.login.store', 'uses' => 'Auth\ClientAuthController@postLogin']);
});

Route::group(['prefix' => 'client', 'middleware' => ['client']], function () {
    Route::get('/', ['as' => 'client.home', 'uses' => 'Client\ClientPagesController@home']);
    Route::get('/logout', ['as' => 'client.login.destroy', 'uses' => 'Auth\ClientAuthController@logout']);
    Route::get('/changePassword', ['as' => 'client.login.edit', 'uses' => 'Auth\ClientAuthController@edit']);
    Route::put('/changePassword', ['as' => 'client.login.update', 'uses' => 'Auth\ClientAuthController@update']);
    Route::resource('/users', 'Client\ClientUserController');
    Route::resource('/businesses', 'Client\ClientBusinessesController');
    Route::resource('/payments', 'Client\ClientPaymentsController');

    Route::resource('/clients', 'ClientsController');
    Route::resource('/features', 'FeaturesController');
    Route::resource('/plans', 'PlansController');
    Route::resource('/categories', 'CategoriesController');
    Route::resource('/fields', 'FieldsController');
    Route::resource('/interests', 'Client\InterestsController');
    Route::get('/handshakes/businesses/{businessId}', [
        'as' => 'client.handshakes.business',
        'uses' => 'Client\HandshakesController@business'
    ]);
    Route::resource('/handshakes', 'Client\HandshakesController');
    Route::get('/inquiries/businesses/{businessId}', [
        'as' => 'client.inquiries.business',
        'uses' => 'Client\InquiryController@business'
    ]);
    Route::resource('/inquiries', 'Client\InquiryController');
    Route::get('/notifications','NotificationController@index');
    Route::get('/notifications/{id}','NotificationController@update');
    Route::get('/notifications/decline/{id}','NotificationController@decline');
});

Route::group(['prefix' => AdminAuthController::ADMIN_URL, 'middleware' => ['admin']], function () {
    Route::get('/', ['as' => 'admin.home', 'uses' => 'AdminPagesController@home']);
    Route::get('/logout', ['as' => 'admin.login.destroy', 'uses' => 'Auth\AdminAuthController@logout']);
    Route::get('/changePassword', ['as' => 'admin.login.edit', 'uses' => 'Auth\AdminAuthController@edit']);
    Route::put('/changePassword', ['as' => 'admin.login.update', 'uses' => 'Auth\AdminAuthController@update']);
    Route::resource('/users', 'UsersController');
    Route::get('/clients/state/{userId}', ['as' => 'manage.clients.state', 'uses' => 'ClientsController@state']);
    Route::resource('/clients', 'ClientsController');
    Route::resource('/features', 'FeaturesController');
    Route::resource('/plans', 'PlansController');
    Route::resource('/categories', 'CategoriesController');
    Route::resource('/fields', 'FieldsController');
    Route::get('/businesses/state/{businessId}', [
        'as' => 'manage.businesses.state',
        'uses' => 'BusinessesController@state'
    ]);
    Route::resource('/businesses', 'BusinessesController');

    Route::resource('/pending', 'PendingBusinessesController');
    Route::resource('/payments', 'PaymentsController');
    Route::get('/newsletter','NewsletterController@index');
    Route::post('/newsletter/email','NewsletterController@email');

});
Route::get('/share/{id}','TestController@index');
Route::post('/email','TestController@sendMail');
Route::get('newuser','NewRegistration@index');
Route::post('newuser/register','NewRegistration@register');
Route::post('upload','TestController@upload');
Route::post('/business/images','TestController@deleteImage');

resources/views/admin/partials/footer.blade.php
<footer class="main-footer">
    <div class="pull-right hidden-xs">
        <b>Version</b> 1.0.0
    </div>
    <strong>Copyright &copy; {{ \Carbon\Carbon::now()->year }} <a href="http://wizag.biz">Wise & Agile Solutions Limited</a>.</strong> All rights
    reserved.
</footer>

resources/views/admin/partials/header.blade.php
<header class="main-header">
    <!-- Logo -->
    <a href="{{ route('admin.home') }}" class="logo">
        <span class="logo-mini"><b>m</b>T</span>
            <span class="logo-lg">
                <img src="{{ asset('images/top-logo.png') }}" alt="mTangaza" class="img-responsive">
            </span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </a>

        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <!-- Notifications: style can be found in dropdown.less -->
                {{--<li class="dropdown notifications-menu">--}}
                    {{--<a href="#" class="dropdown-toggle" data-toggle="dropdown">--}}
                        {{--<i class="fa fa-bell-o"></i>--}}
                        {{--<span class="label label-warning">10</span>--}}
                    {{--</a>--}}
                    {{--<ul class="dropdown-menu">--}}
                        {{--<li class="header">You have 10 notifications</li>--}}
                        {{--<li>--}}
                            {{--<ul class="menu">--}}
                                {{--<li>--}}
                                    {{--<a href="#">--}}
                                        {{--<i class="fa fa-users text-aqua"></i> 5 new members joined today--}}
                                    {{--</a>--}}
                                {{--</li>--}}
                            {{--</ul>--}}
                        {{--</li>--}}
                        {{--<li class="footer"><a href="#">View all</a></li>--}}
                    {{--</ul>--}}
                {{--</li>--}}

                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        {{--<img src="{{ asset('images/top-logo.png') }}" class="user-image" alt="User Image">--}}
                        <span class="hidden-xs">{{ $user->email }}</span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="user-header">
                            <p>
                                {{ $user->email }}
                                <small>Last Login: {{ \Carbon\Carbon::parse($user->last_login)->format('d F Y') }}</small>
                            </p>
                        </li>
                        <li class="user-footer">
                            <div class="pull-left">
                                <a href="{{ route('admin.login.edit') }}" class="btn btn-default btn-flat">Change Password</a>
                            </div>
                            <div class="pull-right">
                                <a href="{{ route('admin.login.destroy') }}" class="btn btn-default btn-flat">Sign out</a>
                            </div>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
</header>

resources/views/admin/partials/sidebar.blade.php
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search...">
              <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                </button>
              </span>
            </div>
        </form>
        <!-- /.search form -->

        <ul class="sidebar-menu">
            <li>
                <a href="{{ route('admin.home') }}">
                    <i class="fa fa-dashboard"></i> <span>Dashboard</span>
                </a>
            </li>
            <li class="header">System Configuration</li>
            <li>
                <a href="{{ route('manage.users.index') }}">
                    <i class="fa fa-users"></i> <span>System Users</span>
                </a>
            </li>
            <li>
                <a href="{{ route('manage.features.index') }}">
                    <i class="fa fa-ticket"></i> <span>Features</span>
                </a>
            </li>
            <li>
                <a href="{{ route('manage.plans.index') }}">
                    <i class="fa fa-cc-visa"></i> <span>Packages & Plans</span>
                </a>
            </li>
            <li>
                <a href="{{ route('manage.categories.index') }}">
                    <i class="fa fa-list-alt"></i> <span>Business Categories</span>
                </a>
            </li>
            <li>
                <a href="{{ route('manage.fields.index') }}">
                    <i class="fa fa-building"></i> <span>Fields of Work</span>
                </a>
            </li>
            <li class="header">Clients & Businesses</li>
            <li>
                <a href="{{ route('manage.clients.index') }}">
                    <i class="fa fa-asl-interpreting"></i> <span>Clients</span>
                </a>
            </li>
            <li>
                <a href="{{ route('manage.businesses.index') }}">
                    <i class="fa fa-suitcase"></i> <span>Businesses</span>
                </a>
            </li>
            <li>
                <a href="{{ route('manage.payments.index') }}">
                    <i class="fa fa-money"></i> <span>Payments</span>
                </a>
            </li>
        </ul>
    </section>
    <!-- /.sidebar -->
</aside>